set(CMAKE_C_COMPILER ${CLOUDABI_TRIPLET}-cc)
set(CMAKE_CXX_COMPILER ${CLOUDABI_TRIPLET}-c++)
set(CMAKE_AR ${CLOUDABI_TRIPLET}-ar CACHE FILEPATH "Archiver")
set(CMAKE_RANLIB ${CLOUDABI_TRIPLET}-ranlib CACHE FILEPATH "Ranlib")
